services:
    ubuntu:
        public: true
        container_name: pkt
        image: jujuns/plok:latest
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 2000m
          memory: 1024Mi
          storage:
            size: 2Gi
            class: standard
